#!/usr/bin/env python3
"""
Simple Database Connection Test
Test Supabase PostgreSQL connection and basic operations
"""

import sys
sys.path.insert(0, '/home/imdeeslt/Study/HCMUS/3.1Term_25-26/Intro2SE/Projects/AI-photofun-Studio/src/backend/backendAI')

from apps.image_gallery.services import image_gallery_service
import uuid


def test_db_connection():
    """Test database connection"""
    print("\n" + "=" * 80)
    print(" TEST 1: Database Connection")
    print("=" * 80)
    
    try:
        conn = image_gallery_service._get_connection()
        print(f"✅ Database connected: {conn}")
        print(f"   Host: {image_gallery_service.DB_CONFIG['host']}")
        print(f"   Database: {image_gallery_service.DB_CONFIG['database']}")
        print(f"   User: {image_gallery_service.DB_CONFIG['user']}")
        return True
    except Exception as e:
        print(f"❌ Connection failed: {str(e)}")
        return False


def test_save_image():
    """Test saving an image"""
    print("\n" + "=" * 80)
    print(" TEST 2: Save Image to Gallery")
    print("=" * 80)
    
    try:
        # Generate test data
        test_user_id = "test_user_" + str(uuid.uuid4())[:8]
        test_image_id = str(uuid.uuid4())
        test_image_url = f"https://file-service-cdal.onrender.com/images/{test_image_id}.jpg"
        
        print(f"\n📝 Test Data:")
        print(f"   User ID: {test_user_id}")
        print(f"   Image URL: {test_image_url}")
        
        # Save image
        result = image_gallery_service.save_image(
            user_id=test_user_id,
            image_url=test_image_url,
            refined_prompt="A beautiful test image generated by AI",
            intent="image_generate",
            metadata={
                "model": "realism",
                "aspect_ratio": "square_1_1",
                "resolution": "2k"
            }
        )
        
        print(f"\n✅ Image saved successfully!")
        print(f"   Image ID: {result.get('image_id')}")
        print(f"   User ID: {result.get('user_id')}")
        print(f"   Intent: {result.get('intent')}")
        print(f"   Created At: {result.get('created_at')}")
        
        return result, test_user_id
    except Exception as e:
        print(f"\n❌ Save failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return None, None


def test_get_user_images(user_id):
    """Test retrieving user images"""
    print("\n" + "=" * 80)
    print(" TEST 3: Retrieve User Images")
    print("=" * 80)
    
    try:
        images = image_gallery_service.get_user_images(user_id=user_id, limit=10)
        
        print(f"\n✅ Retrieved {len(images)} images for user {user_id}")
        
        for i, img in enumerate(images, 1):
            print(f"\n   Image {i}:")
            print(f"      ID: {img.get('image_id')}")
            print(f"      Intent: {img.get('intent')}")
            print(f"      Prompt: {img.get('refined_prompt', '')[:60]}...")
            print(f"      URL: {img.get('image_url', '')[:60]}...")
            print(f"      Created: {img.get('created_at')}")
        
        return True
    except Exception as e:
        print(f"\n❌ Retrieval failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False


def test_filter_by_intent(user_id):
    """Test filtering by intent"""
    print("\n" + "=" * 80)
    print(" TEST 4: Filter by Intent")
    print("=" * 80)
    
    try:
        images = image_gallery_service.get_user_images(
            user_id=user_id,
            intent='image_generate',
            limit=5
        )
        
        print(f"\n✅ Found {len(images)} images with intent='image_generate'")
        return True
    except Exception as e:
        print(f"\n❌ Filter failed: {str(e)}")
        return False


def test_save_multiple_images():
    """Test saving multiple images"""
    print("\n" + "=" * 80)
    print(" TEST 5: Save Multiple Images")
    print("=" * 80)
    
    try:
        test_user_id = "test_user_multi_" + str(uuid.uuid4())[:8]
        test_urls = [
            f"https://file-service-cdal.onrender.com/images/{uuid.uuid4()}.jpg",
            f"https://file-service-cdal.onrender.com/images/{uuid.uuid4()}.jpg",
            f"https://file-service-cdal.onrender.com/images/{uuid.uuid4()}.jpg"
        ]
        
        print(f"\n📝 Saving {len(test_urls)} images for user {test_user_id}")
        
        results = image_gallery_service.save_multiple_images(
            user_id=test_user_id,
            image_urls=test_urls,
            refined_prompt="Multiple test images",
            intent="upscale",
            metadata={"batch": True}
        )
        
        print(f"\n✅ Saved {len(results)} images")
        for i, result in enumerate(results, 1):
            print(f"   {i}. Image ID: {result.get('image_id')}")
        
        return True
    except Exception as e:
        print(f"\n❌ Save multiple failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False


def test_delete_image(user_id, image_id):
    """Test soft delete"""
    print("\n" + "=" * 80)
    print(" TEST 6: Soft Delete Image")
    print("=" * 80)
    
    try:
        print(f"\n🗑️ Deleting image {image_id} for user {user_id}")
        
        success = image_gallery_service.delete_image(user_id, image_id)
        
        if success:
            print(f"✅ Image deleted successfully")
            
            # Verify it's not in active list
            images = image_gallery_service.get_user_images(user_id=user_id)
            deleted_found = any(img.get('image_id') == image_id for img in images)
            
            if not deleted_found:
                print(f"✅ Image not in active list (as expected)")
            else:
                print(f"⚠️ Image still in active list")
        else:
            print(f"⚠️ Delete returned False")
        
        return success
    except Exception as e:
        print(f"\n❌ Delete failed: {str(e)}")
        return False


def main():
    """Run all tests"""
    print("\n" + "🚀 " * 40)
    print("   SUPABASE DATABASE CONNECTION TEST SUITE")
    print("🚀 " * 40)
    
    results = []
    
    # Test 1: Connection
    results.append(("Database Connection", test_db_connection()))
    
    if not results[0][1]:
        print("\n❌ Cannot proceed without database connection")
        return 1
    
    # Test 2: Save Image
    save_result, test_user_id = test_save_image()
    results.append(("Save Image", save_result is not None))
    
    if not save_result:
        print("\n❌ Cannot proceed without successful save")
        return 1
    
    # Test 3: Retrieve Images
    results.append(("Retrieve Images", test_get_user_images(test_user_id)))
    
    # Test 4: Filter by Intent
    results.append(("Filter by Intent", test_filter_by_intent(test_user_id)))
    
    # Test 5: Save Multiple
    results.append(("Save Multiple", test_save_multiple_images()))
    
    # Test 6: Delete Image
    image_id = save_result.get('image_id')
    results.append(("Soft Delete", test_delete_image(test_user_id, image_id)))
    
    # Summary
    print("\n" + "=" * 80)
    print(" TEST SUMMARY")
    print("=" * 80)
    
    passed = sum(1 for _, result in results if result)
    total = len(results)
    
    for name, result in results:
        status = "✅ PASSED" if result else "❌ FAILED"
        print(f"   {status}: {name}")
    
    print(f"\n📊 Results: {passed}/{total} tests passed")
    
    if passed == total:
        print("\n🎉 All database tests passed!")
        print("\n✅ Supabase connection working!")
        print("✅ CRUD operations working!")
        print("✅ Ready for AI service integration!")
        return 0
    else:
        print(f"\n⚠️ {total - passed} test(s) failed")
        return 1


if __name__ == "__main__":
    exit(main())
