# Generated by Django 5.2.7 on 2025-10-27 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageGenerationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prompt", models.TextField(help_text="Text prompt for generation")),
                (
                    "negative_prompt",
                    models.TextField(blank=True, default="", help_text="Negative prompt"),
                ),
                ("width", models.IntegerField(default=512)),
                ("height", models.IntegerField(default=512)),
                ("num_inference_steps", models.IntegerField(default=50)),
                ("guidance_scale", models.FloatField(default=7.5)),
                ("seed", models.IntegerField(blank=True, null=True)),
                (
                    "generated_image",
                    models.ImageField(blank=True, null=True, upload_to="generated_images/"),
                ),
                ("model_used", models.CharField(default="stable-diffusion", max_length=100)),
                (
                    "processing_time",
                    models.FloatField(default=0.0, help_text="Processing time in seconds"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "image_generation_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="image_gener_created_3e5373_idx"),
                    models.Index(fields=["status"], name="image_gener_status_c5e820_idx"),
                ],
            },
        ),
    ]
