# Generated by Django 5.2.7 on 2025-10-27 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("intent_type", models.CharField(max_length=50)),
                ("template", models.TextField(help_text="Template with {placeholders}")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("assistant", "Assistant Message"),
                            ("system", "System Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_prompt", models.TextField(help_text="Original user input")),
                (
                    "refined_prompt",
                    models.TextField(blank=True, help_text="Refined prompt by LLM", null=True),
                ),
                (
                    "detected_intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("image_generation", "Image Generation"),
                            ("image_edit", "Image Editing"),
                            ("face_swap", "Face Swap"),
                            ("background_removal", "Background Removal"),
                            ("general", "General Query"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(blank=True, help_text="Confidence score 0-1", null=True),
                ),
                ("response_text", models.TextField(blank=True, null=True)),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured response data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Total processing time in seconds", null=True
                    ),
                ),
                (
                    "generated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ai_gateway/generated/%Y/%m/%d/"
                    ),
                ),
                (
                    "result_files",
                    models.JSONField(
                        blank=True, default=list, help_text="List of result file paths"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_gateway.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
